### ISSUE TITLE
No files found in report using TypeScript and Jest

### ISSUE THREAD

**Issue by samuelneff** [codecov/codecov-node#105]
I'm trying to setup codecov for the first time and the report seems to be uploading but I get an error about no files found.

https://codecov.io/gh/samuelneff/react-control-flow/commit/010f1b30d4a3fbf72389bdf7703689141cb5fb29

`Jul 30 00:29:36 [WARNING] WARNING No files found in report. {"bot": "samuelneff", "commit": "010f1b3", "public": "t", "service": "github", "slug": "samuelneff/react-control-flow", "task": "upload"}`

The project structure is like this:

```
project
|-coverage
|-dist-test
|---src
|---test
|-src
|-test
```

The TypeScript files are in `/src/*.tsx` and `/test/*.tsx` and during compilation they're output to `/dist-test/*`. The tests and code coverage report run ok and the coverage report is generated at `/coverage/clover.xml`.

I tried several different combinations in `codecov.yml` but nothing seems to work. Latest:

```yml
fixes:
  - "dist-test/"
```

https://github.com/samuelneff/react-control-flow

https://travis-ci.org/samuelneff/react-control-flow

https://codecov.io/gh/samuelneff/react-control-flow

Thanks,

Sam

**Comment by eddiemoore** [comment]
@samuelneff can you try passing the file with the `-f` flag
```bash
codecov -f ./coverage/clover.xml
```

**Comment by asennikov** [comment]
I'm having the same issue with typescript and Jest on our codecov enterprise installation:

`-f` with path to `clover.xml` didn't help
![image](https://user-images.githubusercontent.com/1835550/50044207-19864a80-0091-11e9-9b1f-c7fb2ba4edc7.png)

![image](https://user-images.githubusercontent.com/1835550/50044212-230fb280-0091-11e9-875a-874071a7fb21.png)

is there a way to see some debug output of what exactly it thinks is wrong in the uploaded files?

**Comment by asennikov** [comment]
nevermind, my issue was happening because I was using the codecov.io/bash uploader instead of our enterprise version.
