### ISSUE TITLE
CodeCov not working with AVA

### ISSUE THREAD

**Issue by joshuaquek** [codecov/codecov-node#113]
I am using AVA for testing and even though the codecov runs successfully on Travis CI, on CodeCov I am getting a blank page.

A few other users are also experiencing this:
https://cmty.app/nuxt/nuxt.js/issues/c719

In my `package.json` file, inside the scripts section:
```javascript
...
"travis-test": "nyc --reporter=html --reporter=text ava;"
"report-coverage": "nyc report --reporter=text-lcov > coverage.lcov; ./node_modules/.bin/codecov;"
...
```

In my .travis.yml file:
```
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10"
script:
- npm run travis-test
- npm run report-coverage
```

Any idea on how I can get this working?

**Comment by eddiemoore** [comment]
Are any code coverage reports getting generated correctly when nyc gets run?

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if you are still experiencing issues, please open a ticket in our [community boards](https://community.codecov.io)
