### ISSUE TITLE
Root paths with spaces throw exception

### ISSUE THREAD

**Issue by josh-byster** [codecov/codecov-node#115]
If I have a project with root `/Users/Documents/a b/Projects`, I get the following error:
```
find: /Users/Documents/a: No such file or directory
find: b/Projects: No such file or directory
```
So it looks like a simple issue that the spaces are not being escaped correctly. The problematic line may be here:
https://github.com/codecov/codecov-node/blob/e427d900309adb50746a39a50aa7d80071a5ddd0/lib/codecov.js#L396

**Comment by cnaccio** [comment]
Having the same issue. How to fix?

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if you are still experiencing issues, please open a ticket in our [community boards](https://community.codecov.io)
