### ISSUE TITLE
Codecov reports upload but does not process report

### ISSUE THREAD

**Issue by Thomas-Langlais** [codecov/codecov-node#120]
This is my .codecov.yml file
```
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

fixes:
  - "/home/travis/build/::"
```

Here is the log
```
$ nyc report --reporter=text-lcov > coverage.lcov && codecov
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.1.0
==> Detecting CI Provider
    Travis CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: '3efd2321db4376e49f30653174c8c828dad03f05',
  branch: 'thomas/codecov-setup',
  package: 'node-v3.1.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/travis/build/benmacdonald/capstone -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + /home/travis/build/benmacdonald/capstone/backend/api/coverage.lcov
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/benmacdonald/capstone/commit/3efd2321db4376e49f30653174c8c828dad03f05
```
From this I the failed to process reports.

Anyone can point me in the right direction or have the solution?

**Comment by styfle** [comment]
I have the same problem.

I tried both `nyc` and `c8` and both have the same problem:  successfully uploaded report but visiting the url says "There was an error processing coverage reports."

![image](https://user-images.githubusercontent.com/229881/56374251-b6d4c500-61d0-11e9-9e8b-f0050aa26fe0.png)

**Comment by rolznz** [comment]
Tried for hours and then switched to coveralls... instant success.

**Comment by drazisil** [comment]
Hi @rolznz 

Looking at your raw report, your coverage file is including the full path, so you would need https://docs.codecov.io/docs/fixing-paths to help Codecov match the files in the report to the files in the repo.

@Thomas-Langlais and @styfle , if you are still having issues can you share a recent commit so I can check the logs?

**Comment by styfle** [comment]
Hi @drazisil 

I fixed this in a PR by adding `ts-node` to the tape test runner (since my code and tests are written in TypeScript I guess codecov didnt work with the normal output `dist` folder).

https://github.com/zeit/tracing-js/pull/26

**Comment by drazisil** [comment]
@styfle that's correct. Since we need to match the files in the report to files in the repo, you have to run the coverage against the typescript files as the dist files aren't in the commit for us to see.

**Comment by rolznz** [comment]
@drazisil turns out I had the same problem as @styfle (I was running the coverage against Javascript rather than Typescript). After that, no path fixes were needed to get it running.

Thanks!

**Comment by vroyibg** [comment]
same here, report uploaded successfully but stay "processing" forever
![image](https://user-images.githubusercontent.com/19463853/67684421-bca03400-f9c5-11e9-97aa-ba477bc8c0b0.png)

**Comment by marxjmoura** [comment]
The same here, as described by @vroyibg 

![Screenshot from 2019-11-02 16-38-16](https://user-images.githubusercontent.com/9284822/68076100-63524f00-fd8f-11e9-8faa-6fef9aa683e2.png)

**Comment by d2ci8xc5** [comment]
Any updates on this? Currently facing the same problem as @vroyibg and @marxjmoura. Apparently there might be [outages](https://community.codecov.io/t/report-stuck-in-processing-unable-to-find-report-content-in-storage-archive/569/5) on their side.
#### reports
- [codecov](https://codecov.io/gh/d2ci8xc5/chip8vm/commits)
- [travis log with successful upload](https://travis-ci.org/d2ci8xc5/chip8vm/jobs/607358959)

**Comment by d2ci8xc5** [comment]
pushing again seems to fix the problem for me

**Comment by spaceone** [comment]
I think I have the same problem in https://codecov.io/gh/univention/python-notifier. It also says `Unable to find commit in GitHub`.

**Comment by drazisil** [comment]
The majority of these issues have been fixed, if you are still seeing this please contact us on https://community.codecov.io. This is not an uploader issue.

**Comment by s1mrankaur** [comment]
Facing the same issue! Why is it so difficult to get working?
