### ISSUE TITLE
Error: sending Coverage, Error: Token is required 

### ISSUE THREAD

**Issue by abubakarmani1** [codecov/codecov-node#126]
I am trying to run codecov no my public repo i.e. [https://github.com/BlueBaseJS/plugin-console-logger/tree/feature/plugin-console-logger](url) 

**package.json** 

`"report-coverage": "codecov && cat ./coverage/lcov.info | codacy-coverage",`

but I am continuously receiving subjective errors. this repo is although a public repo but I have provided tokens using 

**.codecov.yml** 

`codecov:

  token: :token`

for reference snapshot is attached here: 
<img width="1296" alt="Screenshot 2019-04-17 at 12 59 40 PM" src="https://user-images.githubusercontent.com/12659497/56271792-bfff5c80-6112-11e9-9276-06bcdd07eaab.png">

My goal is to pass the test on travis CI, please guide me if i am doing something wrong here ?

**Travis CI output** 

<img width="1041" alt="Screenshot 2019-04-17 at 1 33 43 PM" src="https://user-images.githubusercontent.com/12659497/56273150-a14e9500-6115-11e9-97cc-21c2590709c9.png">

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if you are still experiencing issues, please open a ticket in our [community boards](https://community.codecov.io)
