### ISSUE TITLE
Not seeing coverage data for code called by worker_thread

### ISSUE THREAD

**Issue by 7-of-9** [codecov/codecov-node#129]
Hi all, 

Is it by-design that in code called by a Node 10 app with --experimental-worker flag, worker_thread code does not seem to produce coverage data? If this should be working, does anybody have any pointers for particular flags or runtime config needed to get codecov to collect data?

I am seeing code files referenced by my worker_thread(s) simply missing from uploaded codecov.io coverage reports, and I'm also seeing unconditional code lines that are definitely being executed during the test pass showing as partially covered, or not covered at all.

An example of missing coverage file report is here: https://codecov.io/gh/Scoop-Tech/scpx-wallet/tree/f275ff0560d2a24a23cabd0993abee2a682d356a

The source project is here: https://github.com/Scoop-Tech/scpx-wallet, and the tests can be run with ```npm run coverage``` -- for example, files in ```./cpu-worker``` and ```./app-worker``` are completely missing from the coverage report.

Many thanks!

        "codecov": "^3.3.0",
        "jest": "20.0.4",

**Comment by thomasrockhu** [comment]
Hi @7-of-9, if this is still an issue, please open a ticket in the `support` section of our [community boards](https://community.codecov.io).
