### ISSUE TITLE
Support nyc

### ISSUE THREAD

**Issue by rgbkrk** [codecov/codecov-node#13]
[Coveralls takes text based reports as piped input](https://github.com/nickmerwin/node-coveralls#nyc):

```js
nyc npm test && nyc report --reporter=text-lcov | coveralls
```

I'd love to know how to pair `nyc` and `codecov`.

**Comment by stevepeak** [comment]
Give this a shot :)

`nyc npm test && nyc report --reporter=text-lcov > coverage.lcov && codecov`

**Comment by rgbkrk** [comment]
Awesome, trying it out now!

**Comment by rgbkrk** [comment]
Works like a champ. I'll submit some instructions to `nyc` in the coveralls section as a PR.
