### ISSUE TITLE
What's the difference between using codecov-bash and codecov-node?

### ISSUE THREAD

**Issue by rafenden** [codecov/codecov-node#136]
According to the [Codecov docs][1], the recommended way is using [codecov-bash][2] for any project:

> The Codecov Bash Uploader is a very unique and original style to uploading reports. It has been a tradition for other products that integrate with different languages to create a specific plugin for each language. We believe this is a bad practice that quickly leads to out-of-date and poorly maintained packages.

So what's the advantage of using [codecov-node][3] for Node.js projects?

Why [codecov-node][3] even exists if it's considered to be a bad practice?

Same question was asked on the `codecov-bash` project: https://github.com/codecov/codecov-bash/issues/178

  [1]: https://docs.codecov.io/docs/about-the-codecov-bash-uploader
  [2]: https://github.com/codecov/codecov-bash
  [3]: https://github.com/codecov/codecov-node

**Comment by thomasrockhu** [comment]
`codecov-bash` is the most-updated uploader supported by the `Codecov` team and also the uploader most recommended. The other uploaders are community-driven but often solve for more specific cases. They can be easier to incorporate into a CI.
