### ISSUE TITLE
Codecov.yml is not getting detected due to absolute paths

### ISSUE THREAD

**Issue by josh-byster** [codecov/codecov-node#138]
Because of the use of `process.cwd()` to get the path for the `yaml` file (which the API [expects](https://docs.codecov.io/v4.3.0/reference#upload) as relative), the path sent to the query is absolute (ex. `/var/www/app/codecov.yml`) and thus does not take effect online. Likely this is the root cause of #79. the suggested change would be to get the relative path rather than the absolute working directory.

**Comment by thomasrockhu** [comment]
Closing this out as we check for the yaml server-side.
