### ISSUE TITLE
No Branch or Commit for Semaphore CI

### ISSUE THREAD

**Issue by gonzofish** [codecov/codecov-node#141]
When I let Codecov detect my CI (Semaphore), I get the following output:

```shell
  | v3.5.0
  | ==> Configuration:
  | Endpoint: https://codecov.io
  | { commit: undefined, branch: undefined, package: 'node-v3.5.0' }
  | ==> Building file structure
  | ==> Generating gcov reports (skip via --disable=gcov)
  | $ find /home/semaphore/talc -type f -name '*.gcno'  -exec gcov  {} +
  | ==> Scanning for reports
  | + /home/semaphore/talc/coverage.lcov
  | ==> Uploading reports
  | HTTP 400
  | missing required properties: [&#39;commit&#39;]
  |  
  | exit code: 0 duration: 5s
```

But if I disable detection & manually use those the env vars that are used in https://github.com/codecov/codecov-node/blob/master/lib/services/semaphore.js, it succeeds.

**Comment by Jmclerck** [comment]
After taking a quick look at this to see if I can figure out what is happening, it looks like the code changes that you link to @gonzofish have not been released yet. If you look at the files in unpkg for v3.5.0, it still seems to be trying to pick up the old environment variables: https://unpkg.com/codecov@3.5.0/lib/services/semaphore.js

I don't _think_ this has been intended to have been included in a release yet either. As v3.5.0 was cut "3 months ago" according to npmjs.com and this file was only changed on the 6th of June. @eddiemoore can probably confirm if my theory is correct 🙏

**Comment by gonzofish** [comment]
well that explains it 🤦‍♂ 

i should've looked at commit dates

**Comment by matteocontrini** [comment]
Is there an estimated timeframe for a release that includes that commit? Thanks

**Comment by fabiendem** [comment]
Meanwhile I am refering to the specific commit (https://github.com/codecov/codecov-node/commit/6167aa8e3138079de445d562f92511ca2bacc3b6) rather than the version 3.5.0 in my `package.json`:
```
{
  "name": "myapp",
  ....
  "devDependencies": {
		...
	    "codecov": "https://github.com/codecov/codecov-node.git#6167aa8e3138079de445d562f92511ca2bacc3b6",
		...
	},
	...
}
```
Does the job.

**Comment by eddiemoore** [comment]
v3.6.0 includes Semaphore v2. Sorry it's taken so long to get back to this

**Comment by gonzofish** [comment]
No problem @eddiemoore thanks for the update and response!
