### ISSUE TITLE
Codecov cannot detect branch name for CI provider CodeBuild

### ISSUE THREAD

**Issue by aiell0** [codecov/codecov-node#148]
I am attempting to use the npm codecov plugin inside CodeBuild, and I am getting errors explaining that codecov cannot get the branch name despite me explicitly passing it in as a parameter. If I don't specify the branch or commit, I get the same error.

![Screen Shot 2019-09-27 at 3 38 17 PM](https://user-images.githubusercontent.com/5505690/65797480-506baf80-e13d-11e9-8de6-29bdadee906d.png)

The token has been removed for security reasons. Assume it is being passed in correctly.

**Comment by aiell0** [comment]
PR: https://github.com/codecov/codecov-node/pull/149

**Comment by eddiemoore** [comment]
Closed in #149
