### ISSUE TITLE
Github API not found

### ISSUE THREAD

**Issue by lemoustachiste** [codecov/codecov-node#154]
Hi,

I am writing because I am a bit at a loss here. I use Travis CI and Github, as always, for this new project.

I have set up a `GITHUB_TOKEN` in Travis with the following permissions: 
- full repo
- admin:org - read:org
- full admin:repo_hook
- user - user:email

These are the options that work in 3 other repositories. In this new repo, I cannot get codecov to work, it fails with 
```
==> Uploading reports

    HTTP 404

GitHub API: Not Found
```

The user has access to the repo and is an admin.
Is there something different in the configuration?

This is my .travis.yml file
```
language: node_js
node_js:
  - "11"
branches:
  only:
  - master
before_script:
- npm run test
- npm run lint
script:
- npm run build
after_script:
- npm run test:coverage
- npm run test:coverage:report
```

and the commands:
```
{...
"test:coverage": "jest --silent --noStackTrace --coverage",
"test:coverage:report": "codecov",
...}
```

Again, this is the configuration that we have in different projects which work fine. Am I missing something?

**Comment by lemoustachiste** [comment]
For what it's worth, semantic release is able to post comments and update the release history on this project with the github token provided.

**Comment by thomasrockhu** [comment]
We have made significant changes since this first issue was made. I'm going to close out, if you still see issues @lemoustachiste, please open a ticket in our [community boards](https://community.codecov.io)
