### ISSUE TITLE
sed: can't read ././codecov.yml: No such file or directory

### ISSUE THREAD

**Issue by garimagupta715** [codecov/codecov-node#165]
![image](https://user-images.githubusercontent.com/53895149/72878636-4f304500-3d21-11ea-9105-357090d51018.png)

getting below error for after adding codecov at github. even i added token_key also. can you please tell what would be wrong here.

here is my codecov.yml file-----------
------------------------------------
name: codecov
on: [push]
jobs:
  build:
    
    runs-on: [ubuntu-latest]
    steps:
      - uses: codecov/codecov-action@v1.0.5
        name: codecov
        with:
          name: codecov
          # Repository upload token - get it from codecov.io
          token: ${{ secrets.CODECOV_TOKEN }} 
          # Path to coverage file to upload
          file:  ./coverage.xml # optional
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: unittests # optional
          # Specify the location of the .codecov.yml config file
          yml: ./codecov.yml # optional
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true # optional

----------------

**Comment by nguyenphongcgp** [comment]
Me either

**Comment by thomasrockhu** [comment]
@garimagupta715, @nguyenphongcgp this shouldn't be necessary anymore as Codecov only takes a look at the yml server-side.
