### ISSUE TITLE
Partial lines

### ISSUE THREAD

**Issue by spmeesseman** [codecov/codecov-node#168]
Hello

First off thank for all the great work, I am fascinated with the tool now that I have learned it a bit, even though Ive been using it for a year+ now.

Yesterday, afet making changes to improve coverage, my iniital changes got me an 89% coverage rate.  However, since then, all runs are producing coverage 10-15% less.

I am having some issues but maybe I just am missing something.  I have a Typescript project, VSCode Extension (vscode-taskexplorer).

From what I can see, for some reason there are a lot of lines being marked in yellow now as partial.   Simple "if" statements with one parameter are being marked in yellow (some of them).

Here is an example comparing the same code in two different report uploads.  Why would they be different?  The "if" statements in the first report are considered covered, but those same lines in the 2nd link are not?

https://codecov.io/gh/spmeesseman/vscode-taskexplorer/src/431b456ed89ebc29f635699909a9ccb9441066dd/src/taskProviderScript.ts

https://codecov.io/gh/spmeesseman/vscode-taskexplorer/src/fddeac37ad2be1c7b8da63e4d4d9f89e1baf0ece/src/taskProviderScript.ts

The two large screenshots show the same function, but as you can see one has a covered if statement, the other is marked as partial, not sure how an if with one param becomes partial?

What might be happening, or is there something I dont understand?

Thanks for any help in advance!!!
![1](https://user-images.githubusercontent.com/48744816/74759371-b10f9c00-5246-11ea-9065-11a79957d5e0.png)
![3](https://user-images.githubusercontent.com/48744816/74759373-b1a83280-5246-11ea-935a-ee55274ac829.png)
![4](https://user-images.githubusercontent.com/48744816/74759374-b240c900-5246-11ea-960f-58ecb02bd041.png)

**Comment by spmeesseman** [comment]
screenshot of the report when viewing the coverage/lcov-report on my local dev machine

![2](https://user-images.githubusercontent.com/48744816/74759420-c7b5f300-5246-11ea-81a5-6059a785cc5e.png)

**Comment by spmeesseman** [comment]
does it get marked as partial if the if evaluates to true every time and that path is always taken?

**Comment by spmeesseman** [comment]
i uploaded reports to azure artifacts, and coverage is what I would expect...  is there something you can do to fix these liens that are being counted as partial?

![6](https://user-images.githubusercontent.com/48744816/74781461-838b1880-526f-11ea-830a-f87d185cc593.png)

**Comment by spmeesseman** [comment]
more info...  for some reason, on one particular run, the coverage displayed on azure devops dropped to 5%.  Lookin at it, very similar to the numbers I see when just running "npm run test" on my local machine.  But because of the way vscode is launched in the separate process, something internal happens and the covered code ends up being the test files.  All of the files that are used by the actual vscode extension read "0%" coverage.  Thats another story.  But the Devops numbers were exactly these.  Interestinly enough, on this run, the Codecov coverage shot up to 89%, and all those partial marks disappeared.  On the next run, went back to normal, Azure at 88% and Codecov at 80, with all of the partial lines marked again.  I am so confused how this might be happening, its driving me crazy haha

**Comment by eddiemoore** [comment]
Hi @spmeesseman This might be better to be asked on the community page https://community.codecov.io/

**Comment by spmeesseman** [comment]
thanks, i did figure out what was happening.  The test running in a Windows container, using Node10, and Code Insiders, causes this behavior in the Cobertura test.  With Node 8 everything works ok.  Interestingly, in the lcov report though, the Node10 insiders test is the one of the ones producing > 90% coverage rate in the lcov coverage report.

I still think the calculation is wrong on the codecov website, wherever that is happening.  The following 2 lines of code is only considered 50% covered by Codecov, but 100% covered by Azure

if (true) {
    console.log('why are these two lines only 50% covered because the evaluation nevr=er fails never fails? that doesn't make any sense)
}

is that a community thing?

thanks for your help!!

**Comment by eddiemoore** [comment]
Yeah I'd say add it to the community page

**Comment by sinkcup** [comment]
I have this question too.

why codecov percentage is not the same as jest?

https://github.com/sinkcup/coverage-badge
https://app.codecov.io/gh/sinkcup/coverage-badge/blob/main/src/main.js

![image](https://user-images.githubusercontent.com/4971414/143270227-f5672ced-8fc2-4a07-b777-7289e5a82508.png)
![image](https://user-images.githubusercontent.com/4971414/143270318-46f6d32d-e38f-4173-a7ed-fedc73c7d607.png)
