### ISSUE TITLE
Monorepo and relative paths

### ISSUE THREAD

**Issue by ldiqual** [codecov/codecov-node#170]
We have a monorepo using yarn workspaces that looks like this:

```
packages/
  foo/
    coverage/
      lcov.info
    src/
      index.ts
  bar/
    coverage/
      lcov.info
    src/
      index.ts
```

Each package generates coverage using its own testing mechanism, and `lcov.info` contains paths relative to each package (eg `src/index.ts` as opposed to `packages/foo/src/index.ts`). As a result, codecov doesn't seem to properly handle paths since they don't match the git structure.

[Fixing paths](https://docs.codecov.io/docs/fixing-paths) can't work because there's nothing in `src/index.ts` that says what package we should rename the path with.

Is there a way for codecov to handle a structure like this? Maybe multiple uploads per commit from each subfolder? Or a prefix depending on the subfolder?

**Comment by eddiemoore** [comment]
Hi @ldiqual I'm not quite sure why the fixing paths wouldn't work. Mind if I direct you to the community page https://community.codecov.io/ so that the core Codecov team can help out.
