### ISSUE TITLE
Error processing coverage reports

### ISSUE THREAD

**Issue by uo264074** [codecov/codecov-node#175]
Hello. My team and I are developing a [SOLID app](https://github.com/Arquisoft/viade_en1a) and we are having an issue with Codecov.
This is what we get when Travis executes Codecov:

`...
PASS src/App.test.js
Test Suites: 38 passed, 38 total
Tests:       68 passed, 68 total
Snapshots:   0 total
Time:        17.628s
Ran all test suites.

==> Detecting CI Provider
    Travis CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{
  commit: 'efcf97dfb49aa5dc38c70ebe2dfa1137e607badc',
  branch: 'master',
  package: 'node-v3.6.5'
}
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    Failed to run gcov command.
==> Scanning for reports
    X Failed to read file at 
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/Arquisoft/viade_en1a/commit/efcf97dfb49aa5dc38c70ebe2dfa1137e607badc
The command "npm test && codecov" exited with 0.`

But the results we obtain are 0.00% and, if we try to visualize de report, it says "There was an error processing coverage reports".

**Comment by hootener** [comment]
@uo264074 This issue is very likely related to something specific with your use case and not the codecov-node module itself. Please email support@codecov.io with this issue.
