### ISSUE TITLE
Partial lines coverage

### ISSUE THREAD

**Issue by AdrianInsua** [codecov/codecov-node#176]
Hi, i'm having problems with codecov coverage results.

i've just included codecov in my project after implements all tests to have a 100% coverage in lcov report, but codecov shows only a 85% of coverage.

Digging in codecov files i've seen that all if statements are marked as partial, even if code inside is correctly tested, i think this behaviour is not correct.

This screenshot is from codecov report:
![image](https://user-images.githubusercontent.com/14206412/80928949-99a57100-8da8-11ea-8492-8d4b7e6a6e83.png)

And this one is from lcov report:
![image](https://user-images.githubusercontent.com/14206412/80928965-b04bc800-8da8-11ea-9f2e-70a8c4cbfe7f.png)

As you can see lines are hitted more than one time, including if statements.

Maybe there is some missconfiguration in my jest config coverage report?

i'm usin node v.13.6.0

**Comment by eddiemoore** [comment]
Hi @AdrianInsua So with the partial coverage when you have conditional statements (`if`'s) you'll need to have tests that cover both "truthey" and "falsey" parts of the function. So it would need to have tests that cover both having `path.start` and also without `path.start` etc. Then that would mark the conditional as covered.

Let me know how you go.

**Comment by AdrianInsua** [comment]
i have a test for that case:
```javascript
test("createPath with empty Object", () => {
    try {
        createPath({});
    } catch (err) {
        expect(err.message).toBe('Cannot read property \'length\' of undefined')
    }
});
```
in this test an error is expected because new Path will fail.

If i comment this test and the other ones that uses this function i get partial lines in lcov too (as expected):
![image](https://user-images.githubusercontent.com/14206412/80951625-83bf9c80-8df8-11ea-8b16-c0435b27f560.png)

FYI i post this test example but all the if statements in my code are marked as partial

**Comment by eddiemoore** [comment]
Have you got the partial coverage set in the codecov.yml file? https://docs.codecov.io/docs/node

**Comment by AdrianInsua** [comment]
Yes, i've tried with and without that config.

Here a link to my codecov.yml (placed in root folder):
https://github.com/AdrianInsua/neo4j-dashboard/blob/fbf5b841c714266b02ca580fd89ecb9e38f5a75b/codecov.yml#L1-L4

and a link to my ci .yml:
https://github.com/AdrianInsua/neo4j-dashboard/blob/fbf5b841c714266b02ca580fd89ecb9e38f5a75b/.github/workflows/ci.yml#L33-L42

**Comment by eddiemoore** [comment]
Seems the tests are not covering the lines properly. As shown in the coverage report that was uploaded to codecov. https://codecov.io/archive/v4/raw/2020-05-03/653E00C2702EC761759D97D99F3FD62F/fbf5b841c714266b02ca580fd89ecb9e38f5a75b/fb98fb27-75c1-492e-9bdc-dfcbe0313f4a.txt You will see the `falsecount="0"` that means that the coverage report that was generated by jest says the conditionals weren't covered correctly by the tests. Perhaps have a look at jest's `.toThrow` https://jestjs.io/docs/en/expect#tothrowerror for some information on how to test thrown errors

**Comment by AdrianInsua** [comment]
Well, `toThrow` tests still getting falsecount="0".

**My Solution**
I added **cobertura** in "coverageReporters" and uploaded `cobretura-coverage.xml`. Now codecov is getting 100% :)

Probably there is something bad in my jest config.... i don't know
