### ISSUE TITLE
fix: uploads timing out on Github Actions

### ISSUE THREAD

**Issue by NoNameProvided** [codecov/codecov-node#188]
When our CI tries to upload a report the upload times out because it cannot access the server at `35.199.43.247:443`.

```
FetchError: request to https://codecov.io/upload/v2?commit=e7322b4137063cb5e1a2cb08e65aeabc010744f5&branch=develop&yaml=%2Fhome%2Frunner%2Fwork%2Fclass-validator%2Fclass-validator%2Fcodecov.yml&token=***&package=node-v3.7.2 failed, reason: connect ETIMEDOUT 35.199.43.247:443
```

Command used to upload:
```
codecov -f ./coverage/clover.xml -t ${{ secrets.CODECOV_TOKEN }} --commit=$GITHUB_SHA --branch=${GITHUB_REF##*/}
```

An example run: https://github.com/typestack/class-validator/runs/943376310

**Comment by dbjorge** [comment]
This isn't specific to Github Actions; our team has been seeing similar flakiness with upload timeouts in Azure Pipelines. Starting approximately 2-3 months ago, we've been seeing about 7% of our PR builds ([11 of 154 in the last 30 days](https://dev.azure.com/accessibility-insights/accessibility-insights-web/_pipeline/analytics/stageawareoutcome?definitionId=38&contextType=build) as of writing) time out after 3 minutes during execution of `npx codecov -t $(CODECOV_TOKEN)`.

It would be great if the implementation here could follow the same guidance that [Codecov's Troubleshooting Guide](https://docs.codecov.io/docs/troubleshooting-guide) suggests to users, ie, use default behavior that assigns a reasonably short timeout to upload requests and retry them on failure. The existing implementation does attempt to have v3 uploads fall back by retrying as a v2 upload once, but it's only one retry and it doesn't use a reasonable timeout value so it's not very useful in practice.

**Comment by dbjorge** [comment]
As a workaround, it seems that codecov-bash *does* implement the suggested timeout/retry strategy (by passing `--retry 5 --retry-delay 2 --connect-timeout 2` to underlying curl commands), so we're going to try switching to that instead of using codecov-node.

**Comment by thomasrockhu** [comment]
Hi all, we've made some updates on our end which should prevent timeouts. If this is still an issue, please open a ticket in the `support` section of our [community boards](https://community.codecov.io).
