### ISSUE TITLE
dependency issue, execSync ultimately relies on graceful-fs @ 1.2.3 which may break with node 7

### ISSUE THREAD

**Issue by binduwavell** [codecov/codecov-node#19]
Dep graph looks like this:
codecov@1.0.1 > execSync@1.0.2 > temp@0.5.1 > rimraf@2.1.4 > graceful-fs@1.2.3

It appears that execSync @ 1.0.2 is the latest version and it has these old deps.

I wonder if you could use cross-spawn @ 4.0.0 instead? If you need output from your spawned command you might find shelljs interesting (0.5.3 works with node 0.10, if you don't mind losing support for older versions of node, you could look at the latest 0.7.0.)

**Comment by philkunz** [comment]
shelljs is the way to go I think. I actually removed codecov from all my builds for now since execSync led to many false positive failed builds. This is a problem on CIs where one can't specify an own Docker image and codecov has to be installed from npm.

**Comment by bmv437** [comment]
I have the same warning as well. It looks like [execSync](https://github.com/mgutz/execSync) is depreciated.

**Comment by franklinyu** [comment]
Further attempts described in #14.

**Comment by d3viant0ne** [comment]
This is also throwing `shasum` errors preventing proxy users from installing anything depending on it in the tree.

**Comment by kof** [comment]
Any chances to get it fixed?

**Comment by eddiemoore** [comment]
Version 2 has been released. execsync has been removed. Should fix all issues.
