### ISSUE TITLE
Automatic report discovery failing on Windows environment.

### ISSUE THREAD

**Issue by Crevil** [codecov/codecov-node#2]
When trying to discover reports automatically on AppVeyor I get the following error on the FIND command:

```
FIND: Parameter format not correct
child_process.js:1389
    throw err;
          ^
Error: Command failed: find . -type f \( -name '*coverage.*' -or -name 'nosetests.xml' -or -name 'jacoco*.xml' -or -name 'clover.xml' -or -name 'report.xml' -or -name 'cobertura.xml' -or -name 'luacov.report.out' -or -name 'lcov.info' -or -name '*.lcov' -or -name 'gcov.info' -or -name '*.gcov' -or -name '*.lst' \) -not -name '*.sh' -not -name '*.data' -not -name '*.py' -not -name '*.class' -not -name '*.xcconfig' -not -name 'Coverage.profdata' -not -name 'phpunit-code-coverage.xml' -not -name 'coverage.serialized' -not -name '*.pyc' -not -name '*.cfg' -not -name '*.egg' -not -name '*.whl' -not -name '*.html' -not -name '*.js' -not -name '*.cpp' -not -name 'coverage.jade' -not -name 'include.lst' -not -name 'inputFiles.lst' -not -name 'createdFiles.lst' -not -name 'coverage.html' -not -name 'scoverage.measurements.*' -not -name 'test_*_coverage.txt' -not -path '*/vendor/*' -not -path '*/htmlcov/*' -not -path '*/home/cainus/*' -not -path '*/virtualenv/*' -not -path '*/js/generated/coverage/*' -not -path '*/.virtualenv/*' -not -path '*/virtualenvs/*' -not -path '*/.virtualenvs/*' -not -path '*/.env/*' -not -path '*/.envs/*' -not -path '*/env/*' -not -path '*/envs/*' -not -path '*/.venv/*' -not -path '*/.venvs/*' -not -path '*/venv/*' -not -path '*/venvs/*' -not -path '*/.git/*' -not -path '*/.hg/*' -not -path '*/.tox/*' -not -path '*/__pycache__/*' -not -path '*/.egg-info*' -not -path '*/$bower_components/*' -not -path '*/node_modules/*' -not -path '*/conftest_*.c.gcov'
FIND: Parameter format not correct

    at checkExecSyncError (child_process.js:1346:13)
    at execSync (child_process.js:1386:13)
    at Object.upload (C:\projects\test-codecov\node_modules\codecov\lib\codecov.js:260:18)
    at Object.<anonymous> (C:\projects\test-codecov\node_modules\codecov\bin\codecov:24:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

See [complete build log here](https://ci.appveyor.com/project/Crevil/test-codecov/build/1.0.17).

AppVeyor runs in a Windows environment and I can see in the source that the module uses `cat` and the syntax of `find` is *nix style. Is this testet on a Windows environment?
I have not been able to get the windows shell to find any files with the syntax used in the [search of reports](https://github.com/codecov/codecov-node/blob/master/lib/codecov.js#L260).

**Comment by lijunle** [comment]
Get into the same trouble. Revert back to the old *codecov.io* package. :disappointed:

**Comment by Tapppi** [comment]
Bumped in to this too, any plans to actually support Appveyor?

**Comment by eddiemoore** [comment]
@Crevil just released version 2. Are you able to try that and let us know if this is still an issue?

**Comment by Crevil** [comment]
@eddiemoore This is still an issue. You are still using a Unix specific command for file discovery as mentioned in the initial issue description: https://github.com/codecov/codecov-node/blob/master/lib/codecov.js#L224

As proposed in #12 you should do this with something like `globby` instead as this is cross platform.

I've set up a minimal project for testing here: https://github.com/Crevil/test-codecov
And an AppVeyor (Windows) build here: https://ci.appveyor.com/project/Crevil/test-codecov-mgdew

**Comment by catdad** [comment]
Same. Doesn't actually work in AppVeyor: https://ci.appveyor.com/project/catdad/coveralls-ci-test/build/master%20%2321/job/4c02fsadr11ht255

Interestingly, when I run `codecov --file=coverage/lcov.info` -- by the way, don't make the mistake of specifying a file using `codecov --file coverage/lcov.info`, because even though it might seem like it should work, it does not -- still fails.

In [Travis](https://travis-ci.org/catdad-experiments/coveralls-ci-test/jobs/212846465), I get this in the output:

```
==> Targeting specific file
    + /home/travis/build/catdad-experiments/coveralls-ci-test/coverage/lcov.info
==> Uploading reports
    Success!
```

In [AppVeyor](https://ci.appveyor.com/project/catdad/coveralls-ci-test/build/job/scy7vm74nabh4ri2), I get this:

```
==> Targeting specific file
    + C:\projects\coveralls-ci-test\coverage\lcov.info
==> Uploading reports
    HTTP 404
Not Found
```

Note that I am sure the file does exist, as it is reporting to coveralls correctly.

**Comment by catdad** [comment]
This kind of thing really feels like a need to implement #29. I admire the effort to try to detect the coverage file, but a user can easily tell you where it is with very little headache.

**Comment by Crevil** [comment]
I'm closing down stale issues and this has been open for a little less than two year now.

**Comment by bruno-garcia** [comment]
I just hit this issue. Too bad it was closed.
