### ISSUE TITLE
docs: node-example overrides travis-ci install phase

### ISSUE THREAD

**Issue by talohana** [codecov/codecov-node#221]
As a Travis CI beginner, I read the [example-node guide section](https://github.com/codecov/example-node#guide) and followed along.

This created [this weird behavior](https://github.com/semantic-release/changelog/issues/96) since the example override the default install phase.

Eventually I fixed it by changing the install phase to:
```yaml
install:
  - yarn --frozen-lockfile
  - yarn global add codecov
```

**Comment by thomasrockhu** [comment]
Hi @talohana, thanks for this. Would you be able to open a PR in `example-node` and link to your fix in the description?
