### ISSUE TITLE
codecov-node doesn't accept piped report

### ISSUE THREAD

**Issue by dotnetCarpenter** [codecov/codecov-node#29]
Currently you can not pipe a report to codecov. E.g. `tap --coverage-report=text-lcov | codecov --disable=gcov` where the lcov report comes from `tap`.

I have a patch that enable support for piping reports but I want to see if #28 is merged before cleaning up the patch and write proper test.

**Comment by stevepeak** [comment]
Is there a way to have pipe options?

```
tap --coverage-report=text-lcov | codecov
-or-
tap --coverage-report=text-lcov > coverage.lcov && codecov
```

**Comment by dotnetCarpenter** [comment]
In #30 you don't need to set any options - codecov-node will listen for input on stdin for 500ms.
Both `tap --coverage-report=text-lcov | codecov`,  `tap --coverage-report=text-lcov > coverage.lcov && codecov` and `tap --coverage-report=lcov && codecov` is supported.
In the former, the lcov data is piped to codecov and in the latter 2, codecov will detect the coverage files.

The former is a bit more clean as it doesn't leave coverage data artifacts in the project.

**Comment by stevepeak** [comment]
@dotnetCarpenter Great job 👍

> PS Working right now on partial line coverage: https://codecov.io/gh/babel/babylon/src/1a00d4781b0a9ccd614e47418af9c6c72d235fcf/src/parser/expression.js

**Comment by sholladay** [comment]
Any updates or thoughts on this?

Some CI servers are crazy slow and this would help a lot by doing everything in memory, without ever going to disk.

**Comment by hadrienk** [comment]
Until the of @dotnetCarpenter is merge, and provided that you have access to process substitution`<()` you can do

```
$ codecov -f <(nyc report --reporter=text-lcov )
[...]
==> Targeting specific file
    + /dev/fd/11
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/hadrienk/[...]
```

**Comment by dotnetCarpenter** [comment]
@hadrienk wouldn't `cat path/to/coverage/report | codecov` also work?

**Comment by dotnetCarpenter** [comment]
@hadrienk oh wait. I thought #30 was merged. It's just closed.

**Comment by eddiemoore** [comment]
Pipe is now available
