### ISSUE TITLE
Bash Uploader Security Update

### ISSUE THREAD

**Issue by BerkeleyTrue** [codecov/codecov-node#298]
I just wanted to verify whether or not this module was affected by the recent security issue.

All signs point to no, but I would feel better if we could get an affirmative no from the codecov team.

**Comment by thomasrockhu** [comment]
@BerkeleyTrue, Tom from Codecov here. Confirming that this module was not affected by the recent security issue.

**Comment by BerkeleyTrue** [comment]
Thank you!
