### ISSUE TITLE
Using Codecov npm package doesn't generate a comment on the PR 

### ISSUE THREAD

**Issue by AhmedAbdoOrtiga** [codecov/codecov-node#299]
When using the npm package in GitHub workflow in a PR, it doesn't generate a comment like the Codecov GitHub action does!

Here's an example of using the npm package(no comment generated): https://github.com/microsoft/accessibility-insights-action/pull/542

and here's an example of the GitHub action Codecov(comment generated): https://github.com/microsoft/accessibility-insights-action/pull/538

**Comment by thomasrockhu** [comment]
Hi @AhmedAbdoOrtiga, please open a ticket in our [community boards](https://communit.codecov.io)

**Comment by AhmedAbdoOrtiga** [comment]
I can't , it keeps telling me "Sorry, new users can only put 10 links in a post."
as a matter of fact, I don't have more than 10 urls, also what if the description needs more than 10 URLS?!
![image](https://user-images.githubusercontent.com/45858632/115091463-6cc07000-9ecc-11eb-8c72-20b8750e9939.png)

**Comment by thomasrockhu** [comment]
@AhmedAbdoOrtiga apologies I bumped that restriction. Would you be able to try now? Sorry for that inconvenience.
