### ISSUE TITLE
Affected by codecov.io Bash Uploader hack ?

### ISSUE THREAD

**Issue by mohanraj-r** [codecov/codecov-node#300]
I am using this project to upload codecov from a public repo to CircleCI without any env vars or tokens. I received an email from codecov.io stating 

> Bash Uploader Security Notice
> ...
> Unfortunately, we can confirm that you were impacted by this security event 

But the [APRIL 15TH, 2021 Bash Uploader Security Update](https://about.codecov.io/security-update/) states:
> All other supported uploaders, such as codecov-ruby, Codecov’s node uploader npm package, etc., use community contributed upload implementations that do not utilize the bash uploader.

This project seems to be [directly uploading the codecov data using the REST API](https://github.com/codecov/codecov-node/blob/master/lib/codecov.js#L182). So I assume users of this project are not affected? Can you please confirm.

**Comment by thomasrockhu** [comment]
Tom from Codecov here. This package is not affected by the recent security update.
