### ISSUE TITLE
GitHub Check does not fail when Threshold crossed

### ISSUE THREAD

**Issue by SanketD92** [codecov/codecov-node#303]
Hello,

I'm trying to integrate CodeCov into a Create React App project (using pnpm) which contains testable code located in various subfolders within the repository. I set both `status.project.threshold` and `status.patch.threshold` in the codecov.yml file to pretty low values (0% as well as 0.1%). I verified that the codecov.yml [file](https://github.com/awslabs/service-workbench-on-aws/blob/5cee2d6816e0a2687f01a2da6113fc19885aa84f/codecov.yml) was valid using the bash validation command. 

I created a dummy [PR](https://github.com/awslabs/service-workbench-on-aws/pull/459) which removes existing unit tests and more than 5% project coverage, in order to trigger codecov thresholds set. This still does not fail my GitHub codecov check.

I'd like to know what configuration is incorrect/missing for this to work correctly. Also, why am I not seeing the codecov-specific checks "codecov/patch" and "codecov/project" as seen in this [PR](https://github.com/SanketD92/service-workbench-on-aws/pull/6)

Looking forward to your response.

**Comment by thomasrockhu** [comment]
@SanketD92, please use our [community boards](https://community.codecov.io) to get support and follow-up to your issue.

But the quick answer is that you should install the [app integration](https://github.com/apps/codecov)
