### ISSUE TITLE
No CI Detected for repo using Travis CI

### ISSUE THREAD

**Issue by lokenx** [codecov/codecov-node#4]
Any idea why codecov isn't working with a repo using Travis CI? There's a `.travis.yml` in root and Travis is working fine on commits. Tests are run using [Lab](https://github.com/hapijs/lab) into `coverage/lcov.info`.

```
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
```

**Comment by stevepeak** [comment]
Hey @lokenx I have not seen Lab before but from first glance it should not impact Codecov's ability to detect the provider.

Can you provide me with your owner/repo name and a commit sha to checkout whats going on. Thanks!

**Comment by lokenx** [comment]
It's Hapi's code runner. It's in the node example repo at bottom.

https://github.com/codecov/example-node

But yeah it shouldn't have any bearing as it can export the files required (and a manual upload with token worked). I'm testing it with the below repo and any recent commit should have travis configured.

https://github.com/lokenx/plex-requests

**Comment by stevepeak** [comment]
Looks like you got this working! Nice job! The token should not be required for travis-ci.org, were you experiencing issues with that?

**Comment by lokenx** [comment]
But that's the problem, unless I pass through a token it says no CI found and doesn't upload anything, so it's not working as intended.

**Comment by lokenx** [comment]
Clean new repo, Travis CI up and working, but Codecov still complaining.

[Repo](https://github.com/lokenx/plex-requests)

```
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: 'e9143548b5ca3f36e72b0bad79360a1223c38102',
  branch: 'master',
  package: 'node-v1.0.1' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find . -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + ./coverage/lcov.info
==> Uploading reports
    HTTP 400 AssertionError

Please provide the repository token to upload reports via `-t :repository-token`
```
