### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by lannonbr** [codecov/codecov-node#408]
So even though the [Feb. 1, 2022 deadline](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) has passed, this still seems to be functioning as I still have repos using it and they act as if nothing has happened, so I was curious when the old uploaders are actually being fully deprecated.

**Comment by skerit** [comment]
I don't get why anything has to change anyway. Why not just make this a wrapper for the new uploader?
Why make it more difficult for us to actually use this?
