### ISSUE TITLE
graceful-fs version deprecated used in rimraf

### ISSUE THREAD

**Issue by dkebler** [codecov/codecov-node#42]
`npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.`

Looks like rimraf is using a very crusty version of graceful-fs
https://github.com/isaacs/rimraf/issues/32

I and many others are using node 7.  Can you use an alternative to rimraf, force it not to use graceful-fs,  or use another package that doesn't depend on this deprecated package.   

Yea I know codecov is just a dev dependency but would prefer not to use packages with such dated dependencies especially when alternatives exist.
```
npm ls graceful-fs
uci-utils@0.0.1 
└─┬ codecov@1.0.1
  └─┬ execSync@1.0.2
    └─┬ temp@0.5.1
      └─┬ rimraf@2.1.4
        └── graceful-fs@1.2.3
```

**Comment by paulondc** [comment]
Hi, 

I'm wondering if there is anybody looking at this issue ?

**Comment by nebulon42** [comment]
Actually the problem here is `execSync` not `rimraf`. `execSync` is no longer maintained. See also #22 and #14.

**Comment by eddiemoore** [comment]
Version 2 has been released. execsync has been removed. Should fix all issues.
