### ISSUE TITLE
Consider bumping minimum supported `node` version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [codecov/codecov-node#44]
`node@0.10` and `node@0.12` are no longer maintained.  If you bump to at least `node@0.12`, you can replace `execSync`, which is [no longer maintained](https://github.com/mgutz/execSync/commit/a441123572111c1fb225c91b019e0b28f35f4ccd), with `child_process.execSync`.

**Comment by eddiemoore** [comment]
Version 2 has been released. execsync has been removed. And min node version set
