### ISSUE TITLE
Consider switching to nyc from istanbul

### ISSUE THREAD

**Issue by JimiC** [codecov/codecov-node#48]
[nyc](https://github.com/istanbuljs/nyc) is much easier to work with and since [istanbul](https://github.com/gotwarlost/istanbul) seems not to be maintained anymore (by the time I'm writing this it's been 7 months without a single commit) it seems prudent to do so.

With `nyc` the `test script` will look like this:
```json
    "test": "nyc mocha"
```
Simple as that.

**Comment by eddiemoore** [comment]
I agree that nyc is much better than istanbul. Will look into updating

**Comment by DiegoRBaquero** [comment]
`nyc` took over, agreed.

**Comment by revelt** [comment]
+1
