### ISSUE TITLE
Partial coverage documentation is unclear

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [codecov/codecov-node#65]
On the [documentation webage](https://docs.codecov.io/docs/node), it says:

```
# only upload the coverage.json file
bash <(curl -s https://codecov.io/bash) -f coverage/coverage.json
```

However, the Node documentation (such as it is) doesn't even suggest using the bash-uploader; it suggests this module.

Although `-f` exists, it's entirely undocumented, as far as I can tell; and to boot, there's no `coverage/coverage.json` by default with at least some of the tools?

For instance, I use `nyc`; there's a custom JSON file in `.nyc_output` — is that what's needed? Or should I be using the `json` reporter? (Which, by the way, doesn't output to STDOUT, so the instructions to redirect `> coverage.json` are unhelpful; turns out, it dumps the output to a file named `coverage-final.json` in your `--report-dir`.)

**Comment by gajus** [comment]
@thomasrockhu What's the answer here?

**Comment by thomasrockhu** [comment]
This uploader should be able to work without specifying the file directly, so I would try using it out of the box. Closing this out, but if it's not working for you, open a ticket in the support section of our [community boards](https://community.codecov.io)
