### ISSUE TITLE
Github Badge sizing is slightly off

### ISSUE THREAD

**Issue by patrickroberts** [codecov/codecov-node#66]
Compare codecov.io's badge to img.shield.io's badge:

[codecov.io]: ![Code Coverage](https://codecov.io/gh/patrickroberts/di-proxy/branch/master/graph/badge.svg)
[img.shield.io]: ![Code Coverage](https://img.shields.io/badge/codecov-100%25-brightgreen.svg)

I know this is very low priority, but it's an aesthetic that I think should be fixed. Would it be possible to mimic img.shields.io's SVG generation algorithm somehow?

I'm guessing the issue is caused by having implemented the badge with only 2-digit percentages in mind.

[codecov.io]: https://codecov.io/
[img.shield.io]: https://img.shield.io/

**Comment by eddiemoore** [comment]
Please move this to https://github.com/codecov/support
