### ISSUE TITLE
Supported node versions?

### ISSUE THREAD

**Issue by ljharb** [codecov/codecov-node#68]
I need to combine coverage on node 0.8, 0.10, and a number of other versions leading up to "latest".

https://travis-ci.org/ljharb/es-abstract/jobs/260881749 implies that codecov doesn't work on node 0.10.

Coverage and testing tools need to work on far older versions than most users are using - can this be fixed?

**Comment by eddiemoore** [comment]
@ljharb We are only supporting v0.12+ which is out of support now for while now. If you need support on older versions of node, I suggest just using the [bash uploader](https://github.com/codecov/codecov-bash).

**Comment by ljharb** [comment]
Seems like codecov isn't going to work then on my or @Airbnb's open source projects then; official platform support is irrelevant to whether libs need to support a node version.

Thanks for the fast response.

**Comment by eddiemoore** [comment]
The bash uploader at can do a lot more than the node module. I suggest trying that out as we dropped support for node v0.10 earlier this year for the node module. The bash uploader will work on any *NIX platform no matter the environment.

**Comment by ljharb** [comment]
Thanks - I'm not sure if it's worth the effort since even when I raised my code coverage to only run on 0.12+, it wasn't able to process my coverage reports :-/ do you have an IRC or gitter channel we could debug that in?

**Comment by eddiemoore** [comment]
Yeah we do. Gitter channel: https://gitter.im/codecov/support
