### ISSUE TITLE
commit: true (HTTP 400) when running with option -c on CircleCI

### ISSUE THREAD

**Issue by michalstocki** [codecov/codecov-node#69]
I run into a problem that when I put into the CircleCI build configuration
```
./packages/core/node_modules/.bin/codecov -c -F unittests
```
 I receive the following output in the console:
```
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v2.2.0
==> Detecting CI Provider
    Circle CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ service: 'circleci',
  build: '8.0',
  job: '8.0',
  commit: 'true',
  branch: '10003-setup-core-application',
  pr: undefined,
  slug: '<correct repo slug>',
  flags: 'unittests',
  token: '<correct token>',
  package: 'node-v2.2.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find . -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + ./packages/core/coverage/clover.xml
    + ./packages/core/coverage/lcov.info
==> Uploading reports
    HTTP 400
commit must match pattern ^\d+:\w{12}|\w{40}$
```
note, that commit has a `true` value instead SHA hash. 
When I remove the `-c` option (removing coverage report after upload) from the command, the coverage is uploaded succesfully (the `commit` property has a correct value)
The problem occurs on both `2.2.0` and `2.3.0` versions of `codecov-node`.

**Comment by eddiemoore** [comment]
Hi @michalstocki
`-c` in the node uploader is currently for the commit sha. So when it is passed without an argument it will make the commit a boolean. So `true`.
If you are looking to clear previous commits, use `-C`

**Comment by michalstocki** [comment]
@eddiemoore Thanks a lot!
