### ISSUE TITLE
Getting "X Failed to read file at " when using Circleci v2.0

### ISSUE THREAD

**Issue by Olian04** [codecov/codecov-node#70]
I'm running the `./node_modules/.bin/codecov` command as the last step of my build job. And as part of the result i get this message: 

```
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/circleci/repo -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    X Failed to read file at 
```

The result is a successful upload to codecov, but the coverage report is corrupted. 
Codecov claims `There was an error processing coverage reports.` and that there were `No files found in report.`.

I'm running my tests with this mocha command: `mocha --recursive -r ts-node/register test/**/*.ts`

Versions: 
* __codecov-node:__ v2.3.0
* __node:__ 7.10
* __circleci:__  2.0
* __mocha:__ 3.5.3

**Comment by stevepeak** [comment]
Can you verify a coverage report was generated? What is the file path name?

**Comment by Olian04** [comment]
@stevepeak Sorry, but how would i do that? Its my first attempt at using any kind of CI or Code coverage tool.

**Comment by stevepeak** [comment]
Can you run your CI locally and check if there are coverage reports generated in the `coverage/` folder? Thanks

**Comment by Olian04** [comment]
@stevepeak There's not even a folder named `coverage`. I feel like I'm missing something essential. Do i need to setup mocha in some way for it to produce coverage files?

**Comment by TomazWang** [comment]
Is there any solution for this? 

I have the same problem here with Travis CI. I use codecov with istanbul and mocha. I got the same message both on travis and at my local environment. No `coverage` folder was created.

```
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/travis/build/TomazWang/tomaz-bot -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    X Failed to read file at 
==> Uploading reports
    Success!
```

Here is what my script looks like.
```bash
istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --require babel-register -R spec && codecov
```

Versions:
- mocha@5.0.0
- istanbul@0.4.5
- node@8.81
- codecov@3.0.0

**Comment by stevepeak** [comment]
To my knowledge, there should be a `coverage/` directory produced. https://github.com/codecov/example-node

When you run tests locally is there no a `coverage/` folder generated?
What is the output of running `istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --require babel-register -R spec`? Is the report printed in stdout?

**Comment by TomazWang** [comment]
There's no `coevrage/` folder created when/after I ran the script locally, and I don't think there are any reports print out. However, I do notice a line `No coverage information was collected, exit without writing coverage information` prints out before the Codecov logo shows up. Maybe it's more of an istanbul's problem than codecov's. The sample project you mentioned was working well though.

```bash
> tomaz-bot@0.0.0 cover /Users/tomaz/Dev/NodeJS/tomaz-bot
> istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- --require babel-register -R spec && codecov

2018-02-13T15:20:59.431Z [TomazBot] info: logger is on!


  testing chatbot/messages/buttonContext.js
    createButtonAction()
      ✓ should create a button action with type as input
      ✓ should create a button action with action name as input
      ✓ should create a button action with text as input
      ✓ should create a button action with label as input
      ✓ should create a button action with data as input
      ✓ should reject label over 20 chars.
      ✓ should throw when type was not provided

  test line/lineAction.js
    createPostbackAction()
      ✓ should create action with type = post back
      ✓ should create action with data

  test convertToLineMessage()
    ✓ should convert a response message to a line message

  convertResMsgToBtnTemp()
    ✓ should convert button context to line button template

  createThumbnail()
    ✓ should create a thumbnail
    ✓ should create a thumbnail with default size

  createButton()
    ✓ should create a template that has type = button
    ✓ should create a template that contains message
    ✓ should create a template that contains only one action
    ✓ should create a template that contains only multiple action

  basic firestore ussage
    ✓ should add a data in collection 'sandbox'

  add sub collection
    ✓ should add a collection under a doc
    ✓ should work


  20 passing (117ms)

No coverage information was collected, exit without writing coverage information
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.0.0
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: 'a2941369c9c8a0ec70a7abdfc244c90c6e231382',
  branch: 'develop',
  package: 'node-v3.0.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /Users/tomaz/Dev/NodeJS/tomaz-bot -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    X Failed to read file at 
==> Uploading reports
    HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
```

**Comment by TomazWang** [comment]
@stevepeak Sorry to bother you. After a little googling with the keyword `No coverage information was collected...`, I found out that it's a problem occurs when using the older version of istanbul with babel. Update it to version 1.1.0-alpha.1 solves the problem.

**Comment by eddiemoore** [comment]
@Olian04 and @TomazWang is this issue all fixed for you?

**Comment by TomazWang** [comment]
@eddiemoore yes, upgrade istanbul fix the issue.
