### ISSUE TITLE
let's update "request" to latest

### ISSUE THREAD

**Issue by revelt** [codecov/codecov-node#74]
Hi guys,

Currently, npm shows deprecation message upon installing:
![screen shot 2017-10-14 at 15 08 56](https://user-images.githubusercontent.com/8344688/31576376-a4051826-b0f1-11e7-93ec-63e6688904d5.png)

This is because we're not using the latest `request` - current-one uses `node-uuid@1.4.8` which has been dropped on latest `request` since (what solves the issue).

I know there was some action happening on #72, but let's check and update the deps; this will have to be done some time anyway.

cheers

**Comment by fguitton** [comment]
Couldn't agree more, as mentioned in #73.

**Comment by aoberoi** [comment]
I’m for it too, as long as we bump the version number to v3 and clearly document which versions of node are supported in the “engines” field of package.json
