### ISSUE TITLE
Does not support path renaming

### ISSUE THREAD

**Issue by alex-dixon** [codecov/codecov-node#79]
Applying configuration to fix relative path resolution as specified here https://docs.codecov.io/docs/fixing-paths is not detected by the library. Because my project requires this in order to view coverage in the browser without getting a 404 from Github I'm currently using https://docs.codecov.io/docs/about-the-codecov-bash-uploader until there is a fix. Thanks!

**Comment by stevepeak** [comment]
Hey @alex-dixon I'm confused at this question. If you do not mind jumping into our in-app chat or [Slack](https://join.slack.com/t/codecov/shared_invite/enQtMzAwNjgxMTk2MDAyLTQxNjhhZWRhY2RkNzcyZTUxZGI3ZGE1MWQ2NjViOTM3ZWEzYmU4NDJjMWUyN2IwY2VlMWU1OGEwNjc0ODAzMzI) we can have a quicker support loop to fix this up. Thank you!
