### ISSUE TITLE
Issues with execsync prevent codecov from installing correctly

### ISSUE THREAD

**Issue by StephanBijzitter** [codecov/codecov-node#8]
Realizing this is an issue of one of your dependencies, I did decide to post it here. After all, I am not interested in your dependency, but in your project.

On Ubuntu 14.04 (vagrant box), the system hangs when compiling native extensions. No errors thrown, no exit code, it just hangs until you manually stop it:

```
npm verb linkBins execSync@1.0.2
npm verb linkMans execSync@1.0.2
npm verb rebuildBundles execSync@1.0.2
npm verb rebuildBundles [ 'temp' ]
npm info install execSync@1.0.2
npm info postinstall tough-cookie@2.2.1
npm verb readDependencies loading dependencies from /home/vagrant/<<company>>/node_modules/codecov/node_modules/request/node_modules/har-validator/node_modules/chalk/node_modules/strip-ansi/package.json
npm verb readDependencies loading dependencies from /home/vagrant/<<company>>/node_modules/codecov/node_modules/request/node_modules/har-validator/node_modules/pinkie-promise/node_modules/pinkie/package.json

> execSync@1.0.2 install /home/vagrant/<<company>>/node_modules/codecov/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
```

On OS X Yosemite, it works... at least it doesn't throw around exit codes, but it still logs a failure:

```

npm install --save-dev codecov

> execSync@1.0.2 install /Users/stephanbijzitter/<<company>>/node_modules/codecov/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
codecov@1.0.1 node_modules/codecov
├── argv@0.0.2
├── urlgrey@0.4.1
├── request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, is-typedarray@1.0.0, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, node-uuid@1.4.7, qs@6.0.2, mime-types@2.1.9, form-data@1.0.0-rc3, combined-stream@1.0.5, aws4@1.2.1, hawk@3.1.3, bl@1.0.1, http-signature@1.1.1, har-validator@2.0.6)
└── execSync@1.0.2 (temp@0.5.1)
```

Running node 0.12.5

**Comment by chester1000** [comment]
+1

Fails to install on travis for node < 5

**Comment by deepsweet** [comment]
+1 here, this `execsync` is a pita for CI like Travis or AppVeyor.

**Comment by stevepeak** [comment]
Do you have suggestions on how to fix this? Maybe remove execsync all-together...

**Comment by isaacs** [comment]
I strongly recommend removing execSync.

Would you accept a PR that refactored it out?

**Comment by isaacs** [comment]
I ask because, now that node-tap uses this module as a dependency for sending coverage to codecov, it's causing a lot of test failures on CI systems, and it appears to me to be a very straightforward refactoring that I'd be happy to help with.

The explicit purpose of this module is to be a part of a CI workflow, so using a dep that fails to build reliably on containers seems like a pretty significant problem.  If synchronous exec'ing is a must-have, then I'll have to switch back to the `codecov.io` module, which appears to be less well supported.

**Comment by StephanBijzitter** [comment]
Looking briefly through the usage of execSync, it does seem like it can easily be refactored by someone who knows how to translate the command-line magic properly. I do believe this would indeed be the cleanest solution.

**Comment by stevepeak** [comment]
> @isaacs Would you accept a PR that refactored it out?

I would. As you can see there are some file-network detection that needs to occur. Would that be possible through the removal of execSync?

**Comment by VanDalkvist** [comment]
Can I ask, do you still working on it? I tried to use Codecov for my node project but I couldn't because of this issue. It seems that codecov-node is not under development anymore

**Comment by Crevil** [comment]
There sure is not a lot going on here. I created #12 some time ago fixing some of the issues with execSync, but no response.

**Comment by elfet** [comment]
Still not working on travis-ci

**Comment by akshayrawat** [comment]
Same problem with CircleCI.

**Comment by eddiemoore** [comment]
@elfet @akshayrawat What version of node are you using?

**Comment by akshayrawat** [comment]
@eddiemoore node v5.0.0

**Comment by eddiemoore** [comment]
Version 2 has been released. execsync has been removed. Should fix all issues.
