### ISSUE TITLE
Bug: Incorrect paths when reporting from AppVeyor

### ISSUE THREAD

**Issue by lholota** [codecov/codecov-node#80]
I've run into an issue with the paths being reported incorrectly. Example of the repository:
/src
  /projectA
    /AppA.js
  /projectB
    /AppB.js

I ran the tests separately for each project and uploaded results of each test run to codecov. The trouble was that the files were reported without the path, the script just used the current working directory as the root so in the report I saw AppA.js and AppB.js next to each other. This doesn't happen with the bash uploader.

I went through the code and I think there's a bug in the Appveyor service - the root property is not set in on the options (https://github.com/codecov/codecov-node/blob/master/lib/services/appveyor.js) AppVeyor provides an environment variable for the repository which you should be able to use: APPVEYOR_BUILD_FOLDER

**Comment by eddiemoore** [comment]
Hi @lholota, you can check out the docs on this here https://docs.codecov.io/docs/fixing-paths 

Also try with the latest version of the codecov package.

Let us know if this helps
