### ISSUE TITLE
Failed to processing `istanbul` reports

### ISSUE THREAD

**Issue by DarthPestilane** [codecov/codecov-node#81]
I'm doing it on travis:
![image](https://user-images.githubusercontent.com/15375753/34023981-bc7ed966-e182-11e7-8adf-636c2174c3db.png)

then I go to codecov, I got this:
![image](https://user-images.githubusercontent.com/15375753/34024003-d96c6390-e182-11e7-917d-9f369e789951.png)

How to fix this.

**Comment by DarthPestilane** [comment]
Anyone ?

**Comment by eddiemoore** [comment]
I looks like you are using the bash uploader. What version are you using?

CC @stevepeak

**Comment by DarthPestilane** [comment]
@eddiemoore 
Yes, I was using the bash uploader.
istanbul version:0.4.5

**Comment by stevepeak** [comment]
@DarthPestilane Thank you for your patience. The report was uploaded with `.js` file coverage but your project is `.ts`.

Can you use https://github.com/SitePen/remap-istanbul to resolve the issue.

> Your [upload is here](https://s3-us-west-2.amazonaws.com/codecov/v4/raw/2017-12-15/6FFA4092B9C1E10E9FC362D3F664B2B7/7ee9d95d82ec35422d34ac1c51d108a149078881/cae215c8-4552-4a44-a30b-73f79300e43b.txt) for reference.

Thank you,
Steve

**Comment by DarthPestilane** [comment]
@stevepeak Thank you!

**Comment by stevepeak** [comment]
@TomPed we need to add a note about Typescript and redirect people to https://github.com/codecov/example-typescript for proper configuration. Thanks

**Comment by eddiemoore** [comment]
Information added to example-typescript
