### ISSUE TITLE
How to combine multiple reports?

### ISSUE THREAD

**Issue by Shyam-Chen** [codecov/codecov-node#87]
Run each test

```bash
# test - 1
$ yarn test:foo

# test - 2
$ yarn test:bar
```

All reports

```
coverage
  - foo
    - lcov.info
    - ...
  - bar
    - lcov.info
    - ...
```

Then how do I combine these reports into one?

**Comment by stevepeak** [comment]
We combine reports automatically, server side, no setup requried.
Just upload them and we do the rest.

More here: https://docs.codecov.io/docs/merging-reports
