### ISSUE TITLE
security vulnerability in dependency tree

### ISSUE THREAD

**Issue by nattySP** [codecov/codecov-node#88]
nsp caught this and fails our builds --
`codecov@3.0.0` > `request@2.81.0` > `hawk@3.1.3` > `hoek@2.x.x`

I think updating `request` should fix the issue.

`hoek`:
https://nodesecurity.io/advisories/566
Vulnerable  <= 4.2.0 || >= 5.0.0 < 5.0.3 
Patched  > 4.2.0 < 5.0.0 || >= 5.0.3

**Comment by davedoesdev** [comment]
This is on the @github security alert system now so anyone using this module will being getting alerts.

**Comment by davedoesdev** [comment]
Note that @github alerts are erroneously saying that hoek@4.2.1 has a vulnerability but it does not (fix was backported to that version: https://github.com/hapijs/hoek/issues/230) - so codecov-node is fine

**Comment by polytypic** [comment]
Version 3.0.3 reintroduces the vulnerability.  See my comment [here](https://github.com/codecov/codecov-node/commit/39dc2d8905dccd9357f30f2f095e962b3506e218#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

**Comment by eddiemoore** [comment]
Thanks for the update. Fixes in 3.0.4
