### ISSUE TITLE
Command for setup on the website is wrong

### ISSUE THREAD

**Issue by queicherius** [codecov/codecov-node#9]
For the lack of a better place to report this: the command in the setup guide (on the actual website) for javascript is wrong.

```
istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec \
  && ./node_modules/codecov.io/bin/codecov

istanbul cover jasmine-node --captureExceptions spec/ \
  && /node_modules/codecov.io/bin/codecov
```

The actual command is `./node_modules/.bin/codecov`, as described in this repo

**Comment by stevepeak** [comment]
Thank you for bringing this to our attention! :+1:

**Comment by queicherius** [comment]
Seems to be fixed in the new docs. 😄
