### ISSUE TITLE
Flags not working - set to '#true'

### ISSUE THREAD

**Issue by lenntt** [codecov/codecov-node#90]
I'm trying to use flags for different type of tags.
but only see a `#true` flag set. is this a bug, or do I misunderstand something? is a codecov.yml required?

- the build installs codecov 3.0.0
- `codecov --clear --flags unittests`
- I see no traces of ' flags' being set in the codecov built output
- In the pr report, the only flag I see is '#true' (https://github.com/lenntt/kinglouie/pull/9)
- everything else seems fine - coverage being uploaded

https://codecov.io/gh/lenntt/kinglouie/commit/386413080cd4dbc668a531755cb5c9bfcf41287b/build

this is my `.travis.yml`:

```
language: node_js
node_js:
  - "stable"

install:
  - npm install
  - npm install -g codecov

script:
  - npm run lint
  - nyc --reporter=lcov mocha --recursive test/unit
  - codecov --clear --flags unittests
  - nyc --reporter=lcov mocha --recursive test/system
  - codecov --clear --flags systemtests
```

**Comment by stevepeak** [comment]
@lenntt Thank you for asking. It may seem trivial, but I believe the format is `--flags=unittests` in Node the `=` is required (at least I believe so from my level of understanding)

**Comment by stevepeak** [comment]
PS the bash uploader can be used in this case too:

```
install:
  - npm install

script:
  - npm run lint
  - nyc --reporter=lcov mocha --recursive test/unit
  - bash <(curl -s https://codecov.io/bash) -C -F unittests
  - nyc --reporter=lcov mocha --recursive test/system
  - bash <(curl -s https://codecov.io/bash) -C -F systemtests
```

**Comment by lenntt** [comment]
Thanks, silly me. The `=` did the trick!


PS @stevepeak I couldn't get the bash uploader to work, the way you mentioned.

```
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=-F&build=54.1&build_url=&name=&tag=&slug=lenntt%2Fkinglouie&service=travis&flags=&pr=9&job=350943361
    -> Pinging Codecov
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Uploading to Codecov
    HTTP 400
commit must match pattern ^\d+:\w{12}|\w{40}$
```
(https://travis-ci.org/lenntt/kinglouie/builds/350943360)

Result never made it to codecov.

**Comment by foolip** [comment]
FWIW, I ran into this as well and once I'd debugged the problem I was able to find this issue. Documenting this in an example would have helped.
