### ISSUE TITLE
Git: Please tag v3.0.2

### ISSUE THREAD

**Issue by ntwb** [codecov/codecov-node#98]
If you could please tag v3.0.2 that would be greatly appreciated when you've a moment to spare, please, and thank you 😄 

v3.0.1 is tagged, v3.0.2 is not:
• https://github.com/codecov/codecov-node/releases/tag/v3.0.1
• https://github.com/codecov/codecov-node/releases/tag/v3.0.2 

Having the Git tags makes for an easy reference to see the differences between versions:
• https://github.com/codecov/codecov-node/compare/v2.3.1...v3.0.1
• https://github.com/codecov/codecov-node/compare/v2.3.1...v3.0.2

**Comment by eddiemoore** [comment]
https://github.com/codecov/codecov-node/releases/tag/v3.0.2

Done and done
