### ISSUE TITLE
Failed to upload using AppVeyor and no repo token

### ISSUE THREAD

**Issue by JimiC** [codecov/codecov-node#99]
As stated in `Codecov` repo settings "Repository Upload Token"

> Note: Token not required for public repositories uploading from Travis, CircleCI or AppVeyor.

token should not be required in AppVeyor.

When doing so, the upload process fails with

```
HTTP 400
Invalid input parameters. See response body for detailed error message.
```
Additionally, no response body is logged, in order to better understand the cause of the failure.

On the contrary, when setting an environment variable with name `CODECOV_TOKEN` (or `codecov_token` see [details](https://github.com/codecov/codecov-node/blob/v3.0.2/lib/codecov.js#L255)) and the token as a value, then the upload succeeds.

Note: Repository is public. Build env: Windows. Language: Node 

Please advice.

**Comment by thomasrockhu** [comment]
Closing due to age. If this is still an issue, please feel free to open a ticket in our [community boards](https://community.codecov.io).
